Repository aws-amplify/aws-sdk-ios, pull requests merged in 2018-05, with the labels that each got.

#827 Declare framework dependencies in podspecs
  AWSCognitoIdentityProvider.podspec
  AWSCore.podspec
Labels: FrameworkBuild, feature request

#915 Fixes 2 incorrect clang pragmas
  AWSCore/UICKeyChainStore/AWSUICKeyChainStore.m
  AWSCore/Utility/AWSLogging.m
Labels: Core, feature request

#666 Propagate S3 errors through NSError object userInfo["Errors"]
  AWSS3/AWSS3TransferUtility.m
  AWSS3Tests/AWSS3TransferUtilityTests.swift
  AWSiOSSDKv2.xcodeproj/project.pbxproj
Labels: S3, feature request, reviewing
