Repository aws-amplify/aws-sdk-ios, pull requests merged in 2018-11, with the labels that each got.

#1083 circleci configuration
  .circleci/config.yml
  CreateCarthageArchive.sh
  cocoapods_release.py
  release_cocapod.py
Labels: pull request, requesting feedback, reviewing

#1100 Update README.md with new documentation
  README.md
Labels: pull request

#1099 Change the xcode version for release carthage job
  .circleci/config.yml
  CreateCarthageArchive.sh
Labels: CI/CD, pull request

#1110 Fix SafariViewController compatibility issue.
  AWSCognitoAuth/AWSCognitoAuth.m
Labels: Cognito, pull request

#1109 fix to SFSafariViewController done button handler
  AWSCognitoAuth/AWSCognitoAuth.m
Labels: Cognito, pull request
