Repository aws-amplify/aws-sdk-ios, pull requests merged in 2019-09, with the labels that each got.

#1824 AWSMobile Client fixes - Balance semaphore's wait and signal calls.
  AWSAuthSDK/Sources/AWSMobileClient/AWSMobileClientExtensions.swift
  AWSAuthSDK/Tests/AWSMobileClientTests/AWSMobileClientCredentialsTest.swift
  AWSAuthSDK/Tests/AWSMobileClientTests/AWSMobileClientTests.swift
  AWSAuthSDK/Tests/AWSMobileClientTests/AWSMobileClientUserAttributeTests.swift
  AWSCore/Authentication/AWSIdentityProvider.m
  CHANGELOG.md
Labels: AWSMobileClient, Pull Request

#1738 Removed deprecated methods
  AWSAuthSDK/Sources/AWSMobileClient/AWSMobileClient.swift
  CHANGELOG.md
Labels: AWSMobileClient, Pull Request

#1812 add support for in-memory configuration to address #1649
  AWSAuthSDK/AWSAuthSDK.xcodeproj/project.pbxproj
  AWSAuthSDK/AWSAuthSDK.xcodeproj/xcshareddata/xcschemes/AWSMobileClient.xcscheme
  AWSAuthSDK/AWSAuthSDKTestApp/AppDelegate.swift
  AWSAuthSDK/AWSAuthSDKTestApp/ViewController.swift
  AWSAuthSDK/Sources/AWSMobileClient/AWSMobileClient.swift
  AWSAuthSDK/Sources/AWSMobileClient/AWSMobileClientExtensions.swift
  AWSAuthSDK/Sources/AWSMobileClient/Internal/_AWSMobileClient.h
  AWSAuthSDK/Sources/AWSMobileClient/Internal/_AWSMobileClient.m
  AWSAuthSDK/Tests/AWSMobileClientTests/AWSMobileClientTests.swift
  AWSAuthSDK/Tests/AWSMobileClientUnitTests/AWSMobileClientConfig.swift
  AWSAuthSDK/Tests/AWSMobileClientUnitTests/AWSMobileClientConfigTests.swift
  AWSAuthSDK/Tests/AWSMobileClientUnitTests/AWSMobileClientInitializerTests.swift
  AWSAuthSDK/Tests/AWSMobileClientUnitTests/Info.plist
  AWSCore/Service/AWSInfo.h
  AWSCore/Service/AWSInfo.m
  AWSCoreTests/AWSCoreTests.m
  CHANGELOG.md
Labels: AWSMobileClient

#1678 Initialize in-memory 'internalCredentials' from keychain
  AWSCognitoIdentityProviderUnitTests/AWSCognitoIdentityProviderUnitTests.m
  AWSCore/Authentication/AWSCredentialsProvider.m
  AWSCoreTests/AWSCognitoCredentialsProviderTests.m
  AWSiOSSDKv2.xcodeproj/project.pbxproj
  CHANGELOG.md
Labels: Cognito, Core, Pull Request

#1840 Added Cancellation token to cancel on going credential fetch
  AWSAuthSDK/AWSAuthSDK.xcodeproj/project.pbxproj
  AWSAuthSDK/Sources/AWSMobileClient/AWSMobileClient.h
  AWSAuthSDK/Sources/AWSMobileClient/AWSMobileClient.swift
  AWSAuthSDK/Sources/AWSMobileClient/AWSMobileClientExtensions.swift
  AWSAuthSDK/Sources/AWSMobileClient/Internal/AWSCognitoCredentialsProvider+Extension.h
  AWSAuthSDK/Tests/AWSMobileClientTests/AWSMobileClientCredentialsTest.swift
  AWSAuthSDK/Tests/AWSMobileClientTests/AWSMobileClientTests.swift
  AWSCore/Authentication/AWSCredentialsProvider.h
  AWSCore/Authentication/AWSCredentialsProvider.m
Labels: AWSMobileClient, Pull Request

#1836 Changing intValue to longLongValue
  AWSS3/AWSS3TransferUtility.m
Labels: Pull Request, S3

#1844 Fixed boolean casting in AWSCognito
  AWSCognitoIdentityProvider/AWSCognitoIdentityUserPool.m
Labels: Pull Request

#1843 Updated AWSMobileClient to access the new header as public
  AWSAuthSDK/Sources/AWSMobileClient/Internal/_AWSMobileClient.h
  AWSAuthSDK/Tests/AWSMobileClientTests/AWSMobileClientBaseTests.swift
  AWSAuthSDK/Tests/AWSMobileClientTests/AWSMobileClientDeviceTests.swift
  AWSAuthSDK/Tests/AWSMobileClientTests/AWSMobileClientPasswordTests.swift
  AWSAuthSDK/Tests/AWSMobileClientTests/AWSMobileClientSignInTests.swift
  AWSAuthSDK/Tests/AWSMobileClientTests/AWSMobileClientSignoutTests.swift
  AWSAuthSDK/Tests/AWSMobileClientTests/AWSMobileClientUserAttributeTests.swift
  AWSMobileClient.podspec
Labels: Pull Request

#1839 Project file cleanup
  AWSiOSSDKv2.xcodeproj/project.pbxproj
Labels: Build, Pull Request

#1826 Add CHANGELOG entry for S3 progress reporting fix
  CHANGELOG.md
Labels: Documentation, Pull Request

#1859 Update CHANGELOG
  CHANGELOG.md
Labels: Documentation, Pull Request

#1925 Palpatim/remove extra imports
  AWSAutoScaling/AWSAutoScalingService.m
  AWSCognitoIdentityProvider/CognitoIdentityProvider/AWSCognitoIdentityProviderService.m
  AWSComprehend/AWSComprehendService.m
  AWSConnect/AWSConnectService.m
  AWSCore/CognitoIdentity/AWSCognitoIdentityService.m
  AWSCore/STS/AWSSTSService.m
  AWSDynamoDB/AWSDynamoDBService.m
  AWSEC2/AWSEC2Service.m
  AWSElasticLoadBalancing/AWSElasticLoadBalancingService.m
  AWSIoT/AWSIoTDataService.m
  AWSIoT/AWSIoTService.m
  AWSKMS/AWSKMSService.m
  AWSKinesis/AWSFirehoseService.m
  AWSKinesisVideo/AWSKinesisVideoService.m
  AWSLambda/AWSLambdaService.m
  AWSLex/AWSLexService.m
  AWSLogs/AWSLogsService.m
  AWSPinpoint/AWSPinpointTargeting/AWSPinpointTargetingService.m
  AWSPolly/AWSPollyService.m
  AWSRekognition/AWSRekognitionService.m
  AWSSES/AWSSESService.m
  AWSSNS/AWSSNSService.m
  AWSSQS/AWSSQSService.m
  AWSSageMakerRuntime/AWSSageMakerRuntimeService.m
  AWSSimpleDB/AWSSimpleDBService.m
  AWSTranscribe/AWSTranscribeService.m
  AWSTranslate/AWSTranslateService.m
  CHANGELOG.md
Labels: Build, Pull Request

#1928 Fix Pinpoint device token
  AWSPinpoint/AWSPinpointEndpointProfile.m
  AWSPinpointTests/AWSPinpointTargetingClientTests.m
  CHANGELOG.md
Labels: Pinpoint, Pull Request

#1927 Fixed configuration unit test failures
  AWSCoreConfigurationTest/AWSCoreConfigurationTest.m
  AWSCoreConfigurationTest/Info.plist
  AWSCoreServiceConfigurationTest/AWSCoreServiceConfigurationTest.m
  AWSCoreServiceConfigurationTest/Info.plist
  AWSCoreTests/Resources/.do-not-delete
  AWSCoreUnitTests/AWSCoreTests.m
  AWSCoreUnitTests/Resources/ec2-input.json
  AWSCoreUnitTests/Resources/ec2-output.json
  AWSCoreUnitTests/Resources/json-input.json
  AWSCoreUnitTests/Resources/json-output.json
  AWSCoreUnitTests/Resources/query-input.json
  AWSCoreUnitTests/Resources/query-output.json
  AWSCoreUnitTests/Resources/rest-json-input.json
  AWSCoreUnitTests/Resources/rest-json-output.json
  AWSCoreUnitTests/Resources/rest-xml-input.json
  AWSCoreUnitTests/Resources/rest-xml-output.json
  AWSKinesisVideoTests/AWSKinesisVideoTests-Bridging-Header.h
  AWSiOSSDKv2.xcodeproj/project.pbxproj
  AWSiOSSDKv2.xcodeproj/xcshareddata/xcschemes/AWSAllTests.xcscheme
  AWSiOSSDKv2.xcodeproj/xcshareddata/xcschemes/AWSCore.xcscheme
  CircleciScripts/run_unittests.sh
Labels: Pull Request, Tests

#1935 Update project settings to Xcode 11/Swift 5.1
  .circleci/config.yml
  AWSAuthSDK/AWSAuthSDK.xcodeproj/project.pbxproj
  AWSAuthSDK/AWSAuthSDK.xcodeproj/xcshareddata/xcschemes/AWSAuthCore.xcscheme
  AWSAuthSDK/AWSAuthSDK.xcodeproj/xcshareddata/xcschemes/AWSAuthSDKAllTargets.xcscheme
  AWSAuthSDK/AWSAuthSDK.xcodeproj/xcshareddata/xcschemes/AWSAuthUI.xcscheme
  AWSAuthSDK/AWSAuthSDK.xcodeproj/xcshareddata/xcschemes/AWSFacebookSignIn.xcscheme
  AWSAuthSDK/AWSAuthSDK.xcodeproj/xcshareddata/xcschemes/AWSGoogleSignIn.xcscheme
  AWSAuthSDK/AWSAuthSDK.xcodeproj/xcshareddata/xcschemes/AWSMobileClient.xcscheme
  AWSAuthSDK/AWSAuthSDK.xcodeproj/xcshareddata/xcschemes/AWSUserPoolsSignIn.xcscheme
  AWSAuthSDK/Sources/AWSMobileClient/AWSMobileClient.swift
  AWSCoreUnitTests/AWSServiceTests.m
  AWSKinesisVideoArchivedMediaTests/AWSKinesisVideoArchivedMediaTests.swift
  AWSKinesisVideoTests/AWSKinesisVideoTests.swift
  AWSS3Tests/AWSS3TransferUtilityTests.swift
  AWSiOSSDKv2.xcodeproj/project.pbxproj
  AWSiOSSDKv2.xcodeproj/xcshareddata/xcschemes/AWSAPIGateway.xcscheme
  AWSiOSSDKv2.xcodeproj/xcshareddata/xcschemes/AWSAllTests.xcscheme
  AWSiOSSDKv2.xcodeproj/xcshareddata/xcschemes/AWSAllTestsHost.xcscheme
  AWSiOSSDKv2.xcodeproj/xcshareddata/xcschemes/AWSAutoScaling.xcscheme
  AWSiOSSDKv2.xcodeproj/xcshareddata/xcschemes/AWSCloudWatch.xcscheme
  AWSiOSSDKv2.xcodeproj/xcshareddata/xcschemes/AWSCognito.xcscheme
  AWSiOSSDKv2.xcodeproj/xcshareddata/xcschemes/AWSCognitoAuth.xcscheme
  AWSiOSSDKv2.xcodeproj/xcshareddata/xcschemes/AWSCognitoIdentityProvider.xcscheme
  AWSiOSSDKv2.xcodeproj/xcshareddata/xcschemes/AWSCognitoIdentityProviderASF.xcscheme
  AWSiOSSDKv2.xcodeproj/xcshareddata/xcschemes/AWSComprehend.xcscheme
  AWSiOSSDKv2.xcodeproj/xcshareddata/xcschemes/AWSConnect.xcscheme
  AWSiOSSDKv2.xcodeproj/xcshareddata/xcschemes/AWSCore.xcscheme
  AWSiOSSDKv2.xcodeproj/xcshareddata/xcschemes/AWSDynamoDB.xcscheme
  AWSiOSSDKv2.xcodeproj/xcshareddata/xcschemes/AWSEC2.xcscheme
  AWSiOSSDKv2.xcodeproj/xcshareddata/xcschemes/AWSElasticLoadBalancing.xcscheme
  AWSiOSSDKv2.xcodeproj/xcshareddata/xcschemes/AWSIoT.xcscheme
  AWSiOSSDKv2.xcodeproj/xcshareddata/xcschemes/AWSKMS.xcscheme
  AWSiOSSDKv2.xcodeproj/xcshareddata/xcschemes/AWSKinesis.xcscheme
  AWSiOSSDKv2.xcodeproj/xcshareddata/xcschemes/AWSKinesisVideo.xcscheme
  AWSiOSSDKv2.xcodeproj/xcshareddata/xcschemes/AWSKinesisVideoArchivedMedia.xcscheme
  AWSiOSSDKv2.xcodeproj/xcshareddata/xcschemes/AWSLambda.xcscheme
  AWSiOSSDKv2.xcodeproj/xcshareddata/xcschemes/AWSLex.xcscheme
  AWSiOSSDKv2.xcodeproj/xcshareddata/xcschemes/AWSLogs.xcscheme
  AWSiOSSDKv2.xcodeproj/xcshareddata/xcschemes/AWSMachineLearning.xcscheme
  AWSiOSSDKv2.xcodeproj/xcshareddata/xcschemes/AWSMobileAnalytics.xcscheme
  AWSiOSSDKv2.xcodeproj/xcshareddata/xcschemes/AWSPinpoint.xcscheme
  AWSiOSSDKv2.xcodeproj/xcshareddata/xcschemes/AWSPolly.xcscheme
  AWSiOSSDKv2.xcodeproj/xcshareddata/xcschemes/AWSRekognition.xcscheme
  AWSiOSSDKv2.xcodeproj/xcshareddata/xcschemes/AWSResource.xcscheme
  AWSiOSSDKv2.xcodeproj/xcshareddata/xcschemes/AWSS3.xcscheme
  AWSiOSSDKv2.xcodeproj/xcshareddata/xcschemes/AWSSES.xcscheme
  AWSiOSSDKv2.xcodeproj/xcshareddata/xcschemes/AWSSNS.xcscheme
  AWSiOSSDKv2.xcodeproj/xcshareddata/xcschemes/AWSSQS.xcscheme
  AWSiOSSDKv2.xcodeproj/xcshareddata/xcschemes/AWSSageMakerRuntime.xcscheme
  AWSiOSSDKv2.xcodeproj/xcshareddata/xcschemes/AWSSimpleDB.xcscheme
  AWSiOSSDKv2.xcodeproj/xcshareddata/xcschemes/AWSTextract.xcscheme
  AWSiOSSDKv2.xcodeproj/xcshareddata/xcschemes/AWSTranscribe.xcscheme
  AWSiOSSDKv2.xcodeproj/xcshareddata/xcschemes/AWSTranslate.xcscheme
  AWSiOSSDKv2.xcodeproj/xcshareddata/xcschemes/Documentation.xcscheme
  CHANGELOG.md
  README.md
Labels: Build, Infrastructure, Pull Request

#1940 Hosted UI test case for update attribute
  AWSAuthSDK/AWSAuthSDK.xcodeproj/project.pbxproj
  AWSAuthSDK/AWSAuthSDKTestApp/Base.lproj/Main.storyboard
  AWSAuthSDK/AWSAuthSDKTestApp/HostedUIUserPoolViewController.swift
  AWSAuthSDK/AWSAuthSDKTestApp/UserDetailsViewController.swift
  AWSAuthSDK/AWSAuthSDKTestAppUITests/AWSAuthSDKTestAppUITests.swift
  AWSAuthSDK/AWSAuthSDKTestAppUITests/AWSHostedUIUserPoolTests.swift
  CHANGELOG.md
Labels: Pull Request

#1734 Fix #1733. Force to obtain new tokens if accessToken is nil
  AWSCognitoAuth/AWSCognitoAuth.m
Labels: Cognito, Pull Request, Reviewing

#1943 DropIn UI - New Password Required flow added.
  AWSAuthSDK/AWSAuthSDK.xcodeproj/project.pbxproj
  AWSAuthSDK/AWSAuthSDKTestApp/Base.lproj/Main.storyboard
  AWSAuthSDK/AWSAuthSDKTestApp/DropInUIUserPoolViewController.swift
  AWSAuthSDK/AWSAuthSDKTestAppUITests/AWSAuthSDKTestAppUITests.swift
  AWSAuthSDK/AWSAuthSDKTestAppUITests/AWSDropInUIUserPoolTests.swift
  AWSAuthSDK/AWSAuthSDKTestAppUITests/AWSHostedUIUserPoolTests.swift
  AWSAuthSDK/Sources/AWSUserPoolsSignIn/AWSUserPoolsUIOperations.m
  AWSAuthSDK/Sources/AWSUserPoolsSignIn/UserPoolsUI/AWSUserPoolNewPasswordRequiredViewController.h
  AWSAuthSDK/Sources/AWSUserPoolsSignIn/UserPoolsUI/AWSUserPoolNewPasswordRequiredViewController.m
  AWSAuthSDK/Sources/AWSUserPoolsSignIn/UserPoolsUI/AWSUserPools.storyboard
  CHANGELOG.md
Labels: AWSMobileClient, Cognito, Pull Request

#1945 Fix IoT tests to use ATS endpoint throughout
  AWSIoTTests/AWSIoTDataManagerTests.swift
  AWSIoTTests/AWSIoTDataTests.m
Labels: IoT, Tests
