Repository aws-amplify/aws-sdk-ios, pull requests merged in 2019-03, with the labels that each got.

#1260 Fix URL session having a 0 timeoutIntervalForResource when using a custom AWSS3TransferUtility
  AWSS3/AWSS3TransferUtility.m
Labels: Pull Request, S3

#1269 run all integration test on circleci
  .circleci/config.yml
  .gitignore
  CircleciScripts/IntegrationTestsConfiguration.json
  CircleciScripts/run_integrationtests.py
Labels: Infrastructure, Pull Request

#1279 Updated integration test to validate Content-Disposition header
  AWSS3Tests/AWSS3TransferUtilityTests.swift
Labels: Pull Request, S3

#1282 Bug fix in transfer utility to resolve issue with serverside encryption using customer provided key
  AWSS3/AWSS3TransferUtility+HeaderHelper.m
  AWSS3Tests/AWSS3TransferUtilityTests.swift
Labels: Pull Request, S3

#1287 Add new features to AWSMobileClient
  AWSAuthSDK/AWSAuthSDK.xcodeproj/project.pbxproj
  AWSAuthSDK/AWSAuthSDK.xcodeproj/xcshareddata/xcschemes/AWSMobileClient.xcscheme
  AWSAuthSDK/AWSAuthSDKTestApp/AppDelegate.swift
  AWSAuthSDK/AWSAuthSDKTestApp/Base.lproj/Main.storyboard
  AWSAuthSDK/AWSAuthSDKTestApp/Info.plist
  AWSAuthSDK/AWSAuthSDKTestApp/ViewController.swift
  AWSAuthSDK/AWSAuthSDKTestAppUITests/AWSAuthSDKTestAppUITests.swift
  AWSAuthSDK/AWSAuthSDKTestAppUITests/Info.plist
  AWSAuthSDK/Sources/AWSMobileClient/AWSMobileClient.h
  AWSAuthSDK/Sources/AWSMobileClient/AWSMobileClient.swift
  AWSAuthSDK/Sources/AWSMobileClient/AWSMobileClientExtensions.swift
  AWSAuthSDK/Sources/AWSMobileClient/AWSMobileOptions.swift
  AWSAuthSDK/Sources/AWSMobileClient/AWSMobileResults.swift
  AWSAuthSDK/Sources/AWSMobileClient/DeviceOperations.swift
  AWSAuthSDK/Sources/AWSMobileClient/Internal/AWSCognitoAuth+Extensions.h
  AWSAuthSDK/Sources/AWSMobileClient/Internal/AWSCognitoAuth+Extensions.m
  AWSAuthSDK/Sources/AWSMobileClient/Internal/_AWSMobileClient.h
  AWSAuthSDK/Sources/AWSMobileClient/Internal/_AWSMobileClient.m
  AWSAuthSDK/Tests/AWSMobileClientTests/AWSMobileClientTests.swift
  AWSCognitoAuth/AWSCognitoAuth.m
  AWSCore/Authentication/AWSCredentialsProvider.m
  AWSMobileClient.podspec
  CHANGELOG.md
Labels: AWSMobileClient, Pull Request

#1300 Fix comprehend test for positive sentiment.
  AWSComprehendTests/AWSComprehendTests.swift
Labels: Pull Request

#1315 [IoT] Fixes username metadata tracking feature
  AWSIoT/AWSIoTDataManager.m
  AWSIoTTests/AWSIoTDataTests.m
Labels: IoT, Pull Request

#1325 create pull request when a model update branch is created
  .circleci/config.yml
Labels: Infrastructure, Pull Request
