Repository aws-amplify/aws-sdk-ios, pull requests merged in 2019-10, with the labels that each got.

#1860 Support for Custom Auth
  AWSAuthSDK/AWSAuthSDK.xcodeproj/project.pbxproj
  AWSAuthSDK/AWSAuthSDK.xcodeproj/xcshareddata/xcschemes/AWSMobileClient.xcscheme
  AWSAuthSDK/Sources/AWSMobileClient/AWSMobileClient.h
  AWSAuthSDK/Sources/AWSMobileClient/AWSMobileClient.swift
  AWSAuthSDK/Sources/AWSMobileClient/AWSMobileClientExtensions.swift
  AWSAuthSDK/Sources/AWSMobileClient/AWSUserPoolOperationsHandler.swift
  AWSAuthSDK/Sources/AWSMobileClient/Internal/AWSCognitoIdentityUserPool+Extension.h
  AWSAuthSDK/Sources/AWSMobileClient/Internal/AWSUserPoolCustomAuthHandler.swift
  AWSAuthSDK/Tests/AWSMobileClientCustomAuthTests/AWSMobileClientCustomAuthTests.swift
  AWSAuthSDK/Tests/AWSMobileClientCustomAuthTests/Info.plist
  AWSAuthSDK/Tests/AWSMobileClientIntegTestApp/AppDelegate.swift
  AWSAuthSDK/Tests/AWSMobileClientIntegTestApp/Assets.xcassets/AppIcon.appiconset/Contents.json
  AWSAuthSDK/Tests/AWSMobileClientIntegTestApp/Assets.xcassets/Contents.json
  AWSAuthSDK/Tests/AWSMobileClientIntegTestApp/Base.lproj/Main.storyboard
  AWSAuthSDK/Tests/AWSMobileClientIntegTestApp/Info.plist
  AWSAuthSDK/Tests/AWSMobileClientTests/AWSMobileClientCredentialsTest.swift
  AWSAuthSDK/Tests/AWSMobileClientTests/AWSMobileClientDeviceTests.swift
  AWSAuthSDK/Tests/AWSMobileClientTests/AWSMobileClientPasswordTests.swift
  AWSAuthSDK/Tests/AWSMobileClientTests/AWSMobileClientSignInTests.swift
  AWSAuthSDK/Tests/AWSMobileClientTests/AWSMobileClientSignoutTests.swift
  AWSAuthSDK/Tests/AWSMobileClientTests/AWSMobileClientTestBase.swift
  AWSAuthSDK/Tests/AWSMobileClientTests/AWSMobileClientTests.swift
  AWSAuthSDK/Tests/AWSMobileClientTests/AWSMobileClientUserAttributeTests.swift
  AWSCognitoIdentityProvider/AWSCognitoIdentityUser.h
  AWSCognitoIdentityProvider/AWSCognitoIdentityUser.m
  AWSCognitoIdentityProvider/AWSCognitoIdentityUserPool.m
  AWSMobileClient.podspec
Labels: Cognito, Pull Request

#1966 Updated the changelog for custom auth
  CHANGELOG.md
Labels: Pull Request

#1962 add support for dark mode on AuthUI (fixes #1953)
  AWSAuthSDK/AWSAuthSDK.xcodeproj/project.pbxproj
  AWSAuthSDK/Sources/AWSAuthCore/AWSAuthUIHelper.h
  AWSAuthSDK/Sources/AWSAuthCore/AWSAuthUIHelper.m
  AWSAuthSDK/Sources/AWSAuthCore/AWSUIConfiguration.h
  AWSAuthSDK/Sources/AWSAuthUI/AWSAuthUIConfiguration.h
  AWSAuthSDK/Sources/AWSAuthUI/AWSAuthUIConfiguration.m
  AWSAuthSDK/Sources/AWSAuthUI/AWSAuthUIViewController.m
  AWSAuthSDK/Sources/AWSAuthUI/AWSSignInViewController.m
  AWSAuthSDK/Sources/AWSAuthUI/SignIn.storyboard
  AWSAuthSDK/Sources/AWSMobileClient/AWSMobileOptions.swift
  AWSAuthSDK/Sources/AWSMobileClient/Internal/_AWSMobileClient.m
  AWSAuthSDK/Sources/AWSUserPoolsSignIn/UserPoolsUI/AWSFormTableDelegate.h
  AWSAuthSDK/Sources/AWSUserPoolsSignIn/UserPoolsUI/AWSFormTableDelegate.m
  AWSAuthSDK/Sources/AWSUserPoolsSignIn/UserPoolsUI/AWSTableInputCell.h
  AWSAuthSDK/Sources/AWSUserPoolsSignIn/UserPoolsUI/AWSTableInputCell.m
  AWSAuthSDK/Sources/AWSUserPoolsSignIn/UserPoolsUI/AWSUserPoolForgotPasswordViewController.h
  AWSAuthSDK/Sources/AWSUserPoolsSignIn/UserPoolsUI/AWSUserPoolForgotPasswordViewController.m
  AWSAuthSDK/Sources/AWSUserPoolsSignIn/UserPoolsUI/AWSUserPoolMFAViewController.h
  AWSAuthSDK/Sources/AWSUserPoolsSignIn/UserPoolsUI/AWSUserPoolMFAViewController.m
  AWSAuthSDK/Sources/AWSUserPoolsSignIn/UserPoolsUI/AWSUserPoolNewPasswordRequiredViewController.m
  AWSAuthSDK/Sources/AWSUserPoolsSignIn/UserPoolsUI/AWSUserPoolSignUpViewController.h
  AWSAuthSDK/Sources/AWSUserPoolsSignIn/UserPoolsUI/AWSUserPoolSignUpViewController.m
  AWSAuthSDK/Sources/AWSUserPoolsSignIn/UserPoolsUI/AWSUserPools.storyboard
  AWSAuthSDK/Sources/AWSUserPoolsSignIn/UserPoolsUI/AWSUserPoolsUIHelper.m
  AWSAuthUI.podspec
  CHANGELOG.md
Labels: Pull Request

#1970 Fix deployment target for TranscribeStreaming
  AWSiOSSDKv2.xcodeproj/project.pbxproj
Labels: Build, Pull Request

#1971 Remove signing id/team from AuthSDK project file
  AWSAuthSDK/AWSAuthSDK.xcodeproj/project.pbxproj
Labels: Build, Pull Request

#1978 Downgrade release_jazzydoc to Xcode 10.3
  .circleci/config.yml
Labels: Build

#1977 Update jazzy documentation for 2.12.0
  docs/reference/AWSMobileClient/Classes.html
  docs/reference/AWSMobileClient/Classes/AWSMobileClient.html
  docs/reference/AWSMobileClient/Classes/DeviceOperations.html
  docs/reference/AWSMobileClient/Classes/SignInUIOptions.html
  docs/reference/AWSMobileClient/Enums.html
  docs/reference/AWSMobileClient/Enums/AWSMobileClientError.html
  docs/reference/AWSMobileClient/Enums/ForgotPasswordState.html
  docs/reference/AWSMobileClient/Enums/IdentityProvider.html
  docs/reference/AWSMobileClient/Enums/SignInState.html
  docs/reference/AWSMobileClient/Enums/SignUpConfirmationState.html
  docs/reference/AWSMobileClient/Enums/UserCodeDeliveryMedium.html
  docs/reference/AWSMobileClient/Enums/UserState.html
  docs/reference/AWSMobileClient/Structs.html
  docs/reference/AWSMobileClient/Structs/Device.html
  docs/reference/AWSMobileClient/Structs/FederatedSignInOptions.html
  docs/reference/AWSMobileClient/Structs/ForgotPasswordResult.html
  docs/reference/AWSMobileClient/Structs/HostedUIOptions.html
  docs/reference/AWSMobileClient/Structs/ListDevicesResult.html
  docs/reference/AWSMobileClient/Structs/SessionToken.html
  docs/reference/AWSMobileClient/Structs/SignInResult.html
  docs/reference/AWSMobileClient/Structs/SignOutOptions.html
  docs/reference/AWSMobileClient/Structs/SignUpResult.html
  docs/reference/AWSMobileClient/Structs/Tokens.html
  docs/reference/AWSMobileClient/Structs/UserCodeDeliveryDetails.html
  docs/reference/AWSMobileClient/Typealiases.html
  docs/reference/AWSMobileClient/badge.svg
  docs/reference/AWSMobileClient/docsets/AWSMobileClient.docset/Contents/Resources/Documents/Classes.html
  docs/reference/AWSMobileClient/docsets/AWSMobileClient.docset/Contents/Resources/Documents/Classes/AWSMobileClient.html
  docs/reference/AWSMobileClient/docsets/AWSMobileClient.docset/Contents/Resources/Documents/Classes/DeviceOperations.html
  docs/reference/AWSMobileClient/docsets/AWSMobileClient.docset/Contents/Resources/Documents/Classes/SignInUIOptions.html
  docs/reference/AWSMobileClient/docsets/AWSMobileClient.docset/Contents/Resources/Documents/Enums.html
  docs/reference/AWSMobileClient/docsets/AWSMobileClient.docset/Contents/Resources/Documents/Enums/AWSMobileClientError.html
  docs/reference/AWSMobileClient/docsets/AWSMobileClient.docset/Contents/Resources/Documents/Enums/ForgotPasswordState.html
  docs/reference/AWSMobileClient/docsets/AWSMobileClient.docset/Contents/Resources/Documents/Enums/IdentityProvider.html
  docs/reference/AWSMobileClient/docsets/AWSMobileClient.docset/Contents/Resources/Documents/Enums/SignInState.html
  docs/reference/AWSMobileClient/docsets/AWSMobileClient.docset/Contents/Resources/Documents/Enums/SignUpConfirmationState.html
  docs/reference/AWSMobileClient/docsets/AWSMobileClient.docset/Contents/Resources/Documents/Enums/UserCodeDeliveryMedium.html
  docs/reference/AWSMobileClient/docsets/AWSMobileClient.docset/Contents/Resources/Documents/Enums/UserState.html
  docs/reference/AWSMobileClient/docsets/AWSMobileClient.docset/Contents/Resources/Documents/Structs.html
  docs/reference/AWSMobileClient/docsets/AWSMobileClient.docset/Contents/Resources/Documents/Structs/Device.html
  docs/reference/AWSMobileClient/docsets/AWSMobileClient.docset/Contents/Resources/Documents/Structs/FederatedSignInOptions.html
  docs/reference/AWSMobileClient/docsets/AWSMobileClient.docset/Contents/Resources/Documents/Structs/ForgotPasswordResult.html
  docs/reference/AWSMobileClient/docsets/AWSMobileClient.docset/Contents/Resources/Documents/Structs/HostedUIOptions.html
  docs/reference/AWSMobileClient/docsets/AWSMobileClient.docset/Contents/Resources/Documents/Structs/ListDevicesResult.html
  docs/reference/AWSMobileClient/docsets/AWSMobileClient.docset/Contents/Resources/Documents/Structs/SessionToken.html
  docs/reference/AWSMobileClient/docsets/AWSMobileClient.docset/Contents/Resources/Documents/Structs/SignInResult.html
  docs/reference/AWSMobileClient/docsets/AWSMobileClient.docset/Contents/Resources/Documents/Structs/SignOutOptions.html
  docs/reference/AWSMobileClient/docsets/AWSMobileClient.docset/Contents/Resources/Documents/Structs/SignUpResult.html
  docs/reference/AWSMobileClient/docsets/AWSMobileClient.docset/Contents/Resources/Documents/Structs/Tokens.html
  docs/reference/AWSMobileClient/docsets/AWSMobileClient.docset/Contents/Resources/Documents/Structs/UserCodeDeliveryDetails.html
  docs/reference/AWSMobileClient/docsets/AWSMobileClient.docset/Contents/Resources/Documents/Typealiases.html
  docs/reference/AWSMobileClient/docsets/AWSMobileClient.docset/Contents/Resources/Documents/index.html
  docs/reference/AWSMobileClient/docsets/AWSMobileClient.docset/Contents/Resources/Documents/search.json
  docs/reference/AWSMobileClient/docsets/AWSMobileClient.docset/Contents/Resources/docSet.dsidx
  docs/reference/AWSMobileClient/docsets/AWSMobileClient.tgz
  docs/reference/AWSMobileClient/docsets/AWSMobileClient.xml
  docs/reference/AWSMobileClient/index.html
  docs/reference/AWSMobileClient/search.json
  docs/reference/AWSMobileClient/undocumented.json
Labels: Documentation

#1975 Remove custom carthage
  .circleci/config.yml
Labels: Build

#1979 Present SignInUI in full screen modal
  AWSAuthSDK/Sources/AWSAuthUI/AWSAuthUIViewController.m
  CHANGELOG.md
Labels: Cognito

#1991 [Polly] Allow specifying 'engine' in URL builder.
  AWSPolly/AWSPollySynthesizeSpeechURLBuilder.h
  AWSPolly/AWSPollySynthesizeSpeechURLBuilder.m
  AWSPollyTests/AWSPollyTests.m
  CHANGELOG.md
Labels: Polly, Pull Request

#1960 IoT tests
  AWSIoT/Internal/AWSIoTMQTTClient.m
  AWSIoT/Internal/MQTTSDK/AWSMQTTSession.m
  AWSIoTFreeRTOSOTATests/AWSIoTFreeRTOSOTATests-Bridging-Header.h
  AWSIoTFreeRTOSOTATests/AtomicValue.swift
  AWSIoTFreeRTOSOTATests/Info.plist
  AWSIoTFreeRTOSOTATests/IoTTesTHelpers.swift
  AWSIoTFreeRTOSOTATests/OTABlocks.swift
  AWSIoTFreeRTOSOTATests/OTAJobResponse.swift
  AWSIoTFreeRTOSOTATests/OTATests.swift
  AWSIoTFreeRTOSOTATests/README.md
  AWSIoTFreeRTOSOTATests/Resources/ota_integ_test.bin
  AWSIoTFreeRTOSOTATests/StreamTests.swift
  AWSIoTFreeRTOSOTATests/SwiftCBOR/AnyCodingKey.swift
  AWSIoTFreeRTOSOTATests/SwiftCBOR/CBOR.swift
  AWSIoTFreeRTOSOTATests/SwiftCBOR/CBORDecoder.swift
  AWSIoTFreeRTOSOTATests/SwiftCBOR/CBOREncodable.swift
  AWSIoTFreeRTOSOTATests/SwiftCBOR/CBOREncoder.swift
  AWSIoTFreeRTOSOTATests/SwiftCBOR/CBORInputStream.swift
  AWSIoTFreeRTOSOTATests/SwiftCBOR/Decoder/CodableCBORDecoder.swift
  AWSIoTFreeRTOSOTATests/SwiftCBOR/Decoder/KeyedDecodingContainer.swift
  AWSIoTFreeRTOSOTATests/SwiftCBOR/Decoder/SingleValueDecodingContainer.swift
  AWSIoTFreeRTOSOTATests/SwiftCBOR/Decoder/UnkeyedDecodingContainer.swift
  AWSIoTFreeRTOSOTATests/SwiftCBOR/Encoder/CodableCBOREncoder.swift
  AWSIoTFreeRTOSOTATests/SwiftCBOR/Encoder/KeyedEncodingContainer.swift
  AWSIoTFreeRTOSOTATests/SwiftCBOR/Encoder/SingleValueEncodingContainer.swift
  AWSIoTFreeRTOSOTATests/SwiftCBOR/Encoder/UnkeyedEncodingContainer.swift
  AWSIoTFreeRTOSOTATests/SwiftCBOR/FixedWidthInteger+Bytes.swift
  AWSIoTFreeRTOSOTATests/SwiftCBOR/README.md
  AWSIoTFreeRTOSOTATests/SwiftCBOR/UNLICENSE
  AWSIoTFreeRTOSOTATests/SwiftCBOR/Util.swift
  AWSIoTTests/AWSIoTTests.m
  AWSIoTUnitTests/Helpers/MQTTDecoderTestHelpers.h
  AWSIoTUnitTests/Helpers/MQTTDecoderTestHelpers.m
  AWSIoTUnitTests/Helpers/TestDataWriter.h
  AWSIoTUnitTests/Helpers/TestDataWriter.m
  AWSIoTUnitTests/Helpers/TestDecoderDelegate.h
  AWSIoTUnitTests/Helpers/TestDecoderDelegate.m
  AWSIoTUnitTests/Helpers/TestMQTTSessionDelegate.h
  AWSIoTUnitTests/Helpers/TestMQTTSessionDelegate.m
  AWSIoTUnitTests/MQTTDecoderTests.m
  AWSIoTUnitTests/MQTTSessionTests.m
  AWSIoTUnitTests/Resources/mqttclient-transcript.base64
  AWSIoTUnitTests/Resources/websocket-transcript.base64
  AWSiOSSDKv2.xcodeproj/project.pbxproj
  AWSiOSSDKv2.xcodeproj/xcshareddata/xcschemes/AWSAllTestsHost.xcscheme
  AWSiOSSDKv2.xcodeproj/xcshareddata/xcschemes/AWSIoT.xcscheme
  CircleciScripts/IntegrationTestsConfiguration.json
Labels: IoT, Tests

#1324 Configurable signup button
  AWSAuthSDK/Sources/AWSAuthUI/AWSAuthUIViewController.m
  AWSAuthSDK/Sources/AWSAuthUI/AWSSignInViewController.m
  AWSAuthSDK/Sources/AWSMobileClient/AWSMobileOptions.swift
  AWSAuthSDK/Sources/AWSMobileClient/Internal/_AWSMobileClient.m
Labels: AWSMobileClient, Pull Request, Requesting Feedback

#2003 Fix Crash in S3 upload data
  AWSS3/AWSS3TransferUtility.m
  AWSS3UnitTests/AWSS3TransferUtilityUnitTests.m
  CHANGELOG.md
Labels: Pull Request

#2007 Palpatim/ota testing
  AWSIoT/Internal/MQTTSDK/AWSMQTTDecoder.m
  AWSIoTFreeRTOSOTATests/Support/AtomicValue.swift
  AWSIoTFreeRTOSOTATests/Support/IoTTesTHelpers.swift
  AWSIoTFreeRTOSOTATests/Support/OTABlocks.swift
  AWSIoTFreeRTOSOTATests/Support/OTAJobResponse.swift
  AWSIoTFreeRTOSOTATests/Support/SwiftCBOR/AnyCodingKey.swift
  AWSIoTFreeRTOSOTATests/Support/SwiftCBOR/CBOR.swift
  AWSIoTFreeRTOSOTATests/Support/SwiftCBOR/CBORDecoder.swift
  AWSIoTFreeRTOSOTATests/Support/SwiftCBOR/CBOREncodable.swift
  AWSIoTFreeRTOSOTATests/Support/SwiftCBOR/CBOREncoder.swift
  AWSIoTFreeRTOSOTATests/Support/SwiftCBOR/CBORInputStream.swift
  AWSIoTFreeRTOSOTATests/Support/SwiftCBOR/Decoder/CodableCBORDecoder.swift
  AWSIoTFreeRTOSOTATests/Support/SwiftCBOR/Decoder/KeyedDecodingContainer.swift
  AWSIoTFreeRTOSOTATests/Support/SwiftCBOR/Decoder/SingleValueDecodingContainer.swift
  AWSIoTFreeRTOSOTATests/Support/SwiftCBOR/Decoder/UnkeyedDecodingContainer.swift
  AWSIoTFreeRTOSOTATests/Support/SwiftCBOR/Encoder/CodableCBOREncoder.swift
  AWSIoTFreeRTOSOTATests/Support/SwiftCBOR/Encoder/KeyedEncodingContainer.swift
  AWSIoTFreeRTOSOTATests/Support/SwiftCBOR/Encoder/SingleValueEncodingContainer.swift
  AWSIoTFreeRTOSOTATests/Support/SwiftCBOR/Encoder/UnkeyedEncodingContainer.swift
  AWSIoTFreeRTOSOTATests/Support/SwiftCBOR/FixedWidthInteger+Bytes.swift
  AWSIoTFreeRTOSOTATests/Support/SwiftCBOR/README.md
  AWSIoTFreeRTOSOTATests/Support/SwiftCBOR/UNLICENSE
  AWSIoTFreeRTOSOTATests/Support/SwiftCBOR/Util.swift
  AWSiOSSDKv2.xcodeproj/project.pbxproj
  CHANGELOG.md
Labels: IoT, Pull Request

#2009 Removed run_ui_test build step
  .circleci/config.yml
Labels: Pull Request, Tests
