Repository aws-amplify/aws-sdk-ios, pull requests merged in 2019-02, with the labels that each got.

#1223 Update config.yml change workflow so that release does not depend on s3 release
  .circleci/config.yml
Labels: Infrastructure, Pull Request

#1094 Added a configurable option to disable & hide the "Create new account" button in the User Pools UI.
  AWSAuthSDK/Sources/AWSAuthUI/AWSAuthUIConfiguration.h
  AWSAuthSDK/Sources/AWSAuthUI/AWSAuthUIConfiguration.m
  AWSAuthSDK/Sources/AWSAuthUI/AWSSignInViewController.m
Labels: Cognito, Pending, Pull Request

#1192 Fixes threading issues in AWSCredentialsProvider
  AWSCore/Authentication/AWSCredentialsProvider.m
Labels: Cognito, Pending, Pull Request

#1240 remove double `the` from document
  AWSCore/Bolts/AWSTask.h
Labels: Core, Pending, Pull Request
