Repository aws-amplify/aws-sdk-ios, pull requests merged in 2020-07, with the labels that each got.

#2852 bug(auth): Fix drop-in ui button background issue
  AWSAuthSDK/Sources/AWSAuthUI/AWSSignInViewController.m
Labels: Cognito, bug

#2858 fix(pinpoint): remove global event source attributes on session end
  AWSPinpoint/AWSPinpointSessionClient.m
Labels: Pinpoint, bug

#2877 Palpatim/use carthage frameworks
  .circleci/config.yml
  CircleciScripts/package.sh
  CircleciScripts/package_sdk.sh
Labels: Build, Pull Request

#2875 test(IoT): Integration test for enhanced custom auth
  AWSIoTTests/AWSIoTDataManagerTests.swift
Labels: IoT

#2900 bug(UICKeychainStore): serialize access to keychain on setData
  AWSCore/UICKeyChainStore/AWSUICKeyChainStore.m
Labels: Cognito
