Repository aws-amplify/aws-sdk-ios, pull requests merged in 2020-02, with the labels that each got.

#2270 EC2 integration test bug fix
  AWSEC2Tests/AWSEC2Tests.m
  CHANGELOG.md
Labels: Bug, EC2, Tests

#2277 fix cocoapod publish deploy logic
  .circleci/config.yml
  CircleciScripts/.python-version
  CircleciScripts/cocoapods_release.py
  CircleciScripts/framework_list.py
Labels: Build, Pull Request

#2287 Fix carthage-archive step by removing unbuilt frameworks
  CircleciScripts/create_carthage_archive.py
Labels: Build

#2289 Remove AWSTranscribeStreaming subspec
  AWSiOSSDKv2.podspec
  CHANGELOG.md
Labels: Build

#2290 Clean up README
  README.md
Labels: Documentation
